// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvAW1ldTyoZS2r5Yfi_Ty22noTXW_nwUk',
    appId: '1:1097160692827:web:3521f175c0fd004f335b7e',
    messagingSenderId: '1097160692827',
    projectId: 'royal-rangers-hravec',
    authDomain: 'royal-rangers-hravec.firebaseapp.com',
    storageBucket: 'royal-rangers-hravec.appspot.com',
    measurementId: 'G-PJBJG7GZZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDwtbA8oRDEQwX_V_SZKr977qhianBxSY',
    appId: '1:1097160692827:android:daf031c60c4fc1a1335b7e',
    messagingSenderId: '1097160692827',
    projectId: 'royal-rangers-hravec',
    storageBucket: 'royal-rangers-hravec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChkcLRTnzIArnrljhdwXoTLHELBLdNz90',
    appId: '1:1097160692827:ios:df9e2da8dc1f1b5f335b7e',
    messagingSenderId: '1097160692827',
    projectId: 'royal-rangers-hravec',
    storageBucket: 'royal-rangers-hravec.appspot.com',
    iosBundleId: 'com.example.hravec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChkcLRTnzIArnrljhdwXoTLHELBLdNz90',
    appId: '1:1097160692827:ios:dbb6d35944ad36e8335b7e',
    messagingSenderId: '1097160692827',
    projectId: 'royal-rangers-hravec',
    storageBucket: 'royal-rangers-hravec.appspot.com',
    iosBundleId: 'com.example.hravec.RunnerTests',
  );
}
